### ISSUE TITLE
hlx build of demo project fails 

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#654]
**Description**
`hlx build` of a newly created project with `hlx demo` fails with the following error:

```
/Users/stefan/Downloads/demo/src/html.htl: Cannot find module './html.pre.js
2019-03-18 16:52:42.428 error: encountered unhandled promise rejection at process level: [object Promise], reason: [object Object]
```

**To Reproduce**
1. Install binary `hlx` (version 0.13.9 or 0.13.10)
2. `hlx demo demo && cd demo && hlx up` 
3. See error

**Expected behavior**
No error, browser launches and renders the project

**Version:**
`0.13.9` and `0.13.10`

**Additional context**
Works with `0.13.8`

**Comment by stefan-guggisberg** [comment]
only the binary builds of `hlx` seem to be affected.

**Comment by stefan-guggisberg** [comment]
Found the root cause: As of version `0.13.9` `helix-cli` doesn't work properly on Node 8.3 anymore. Version `0.13.8` works as expected on Node 8.3.

see #657 

Since the binary `hlx` embeds Node 8.3 it's affected as of version `0.13.9`.

**Comment by tripodsan** [comment]
can you include a more recent node version in the `hlx` binary? for example: `node v8.15.1` ?

**Comment by stefan-guggisberg** [comment]
I already spent 3 days working on porting the packaged Node runtime. It's non trivial. It involves patching Node sources and gyp files :/ More recent Node versions introduce new `fs` methods (e.g. `copyFile`) which need to be ported to support `squashfs`...

**Comment by stefan-guggisberg** [comment]
fixed via workaround 12c5092
closing
