### ISSUE TITLE
`hlx up` fails on node 12.1 but works on node 12.12

### ISSUE THREAD

**Issue by alexkli** [adobe/helix-cli#1190]
**Description**
Running `hlx mytestproject` and then `hlx up --no-local-repo` fails on **nodejs 12.1** with `.../mytestproject/src/html.htl: Cannot find module './html.pre.js'`

However, on latest **nodejs 12.12** it works fine.

Suggest to update the `engine` version range in the `package.json` to reflect that, i.e. `... || > 12.12`.

**Expected behavior**
hlx up works.

**Version:**
`v5.7.0`

**Additional context**

Full output:
```
> node --version
v12.1.0

> hlx up --no-local-repo

Warning: The current node version v12.1.0 does not satisfy 
the supported version range >=8.9 <9.0 || >=10.0 < 11.0.
You might encounter unexpected errors.   

    __ __    ___         
   / // /__ / (_)_ __    
  / _  / -_) / /\ \ / 
 /_//_/\__/_/_//_\_\ v5.7.0
                         
Debugger listening on ws://127.0.0.1:9229/84a95afd-261f-407e-adfa-43c5afa5599e
For help, see: https://nodejs.org/en/docs/inspector
Building project files...
🚨  /Users/alex/Work/code/helix/mytestproject/src/html.htl: Cannot find module './html.pre.js'
Require stack:
- /usr/local/lib/node_modules/@adobe/helix-cli/src/parcel/AdapterJSAsset.js
- /usr/local/lib/node_modules/@adobe/helix-cli/node_modules/parcel-bundler/src/Parser.js
- /usr/local/lib/node_modules/@adobe/helix-cli/node_modules/parcel-bundler/src/Bundler.js
- /usr/local/lib/node_modules/@adobe/helix-cli/node_modules/parcel-bundler/index.js
- /usr/local/lib/node_modules/@adobe/helix-cli/src/build.cmd.js
- /usr/local/lib/node_modules/@adobe/helix-cli/src/up.cmd.js
- /usr/local/lib/node_modules/@adobe/helix-cli/src/up.js
- /usr/local/lib/node_modules/@adobe/helix-cli/src/cli.js
- /usr/local/lib/node_modules/@adobe/helix-cli/index.js
[ERROR] encountered unhandled promise rejection at process level: [object Promise], reason: [object Object]
```

After updating nodejs:
```
> node --version
v12.12.0

> hlx up --no-local-repo

Warning: The current node version v12.12.0 does not satisfy 
the supported version range >=8.9 <9.0 || >=10.0 < 11.0.
You might encounter unexpected errors.   

    __ __    ___         
   / // /__ / (_)_ __    
  / _  / -_) / /\ \ / 
 /_//_/\__/_/_//_\_\ v5.7.0
                         
Debugger listening on ws://127.0.0.1:9229/e1ed99ac-bf58-470c-b472-77b3263612ba
For help, see: https://nodejs.org/en/docs/inspector
Building project files...done 1082ms
[hlx] info: Starting helix-simulator v2.13.9
[hlx] info: Local Helix Dev server up and running: http://localhost:3000/
Note: 
The project does not have a helix-config.yaml which is necessary to 
access remote content and to deploy helix. Consider running 
hlx up --save-config to generate a default config.
[76951] HTTP: listening on port 51280
[hlx] error: Resource not found: /apple-touch-icon-precomposed.png
[hlx] error: Resource not found: /apple-touch-icon.png
```

**Comment by stefan-guggisberg** [comment]
Seems to be related to `Parcel`.  I  verified the issue using node v12.1 & v12.11.0. it doesn't occur on node v12.11.1 and later.

**Comment by stefan-guggisberg** [comment]
resolved via #1191
