### ISSUE TITLE
helix-cli 4.0.2 and newer missing @adobe/htlengine in deployed runtime actions

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#931]
**Description**
The greenkeeper PRs to update helix-cli for the devsite have been failing since 4.0.2. See the following failed CI jobs:

- 4.0.2: https://circleci.com/gh/adobe/developer.adobe.com/2720?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
- 4.0.3: https://circleci.com/gh/adobe/developer.adobe.com/2727?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
- 4.0.4: https://circleci.com/gh/adobe/developer.adobe.com/2734?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack

**To Reproduce**
1. Visit https://adobedevsite.helix-demo.xyz/xd/docs
2. See the error which looks like:

```
{
  "code": "e79xNnpAi1u7m37FWow781fgoK5LJ60c",
  "error": "There was an error processing your request."
}
```

3. The same error can be seen when issuing a request against runtime directly: https://adobeioruntime.net/api/v1/web/developer-adobe-com/github-com--adobe--developer-adobe-com--greenkeeper--adobe-helix-cli-4-0-4-dirty/html?owner=AdobeXD&repo=plugin-docs&ref=master&path=/README.md&selector=&extension=&strain=xd-docs-dev&rootPath=/xd/docs&params=

**Expected behavior**
No runtime action explosions.

**Screenshots**

**Version:**
4.0.2, 4.0.3, 4.0.4

**Additional context**
Runtime activation logs has this interesting tidbit:

```
    "response": {
        "status": "action developer error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "Initialization has failed due to: Error: Cannot find module '@adobe/htlengine'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/nodejsAction/XXHKndDO/html.js:30:5)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"
```

**Comment by filmaj** [comment]
So if I do a request to the `developer-adobe-com/hlx--static` strain, I also see other 'no modules found' errors using 4.0.4, this time of 'request-promise-native'.

**Comment by tripodsan** [comment]
probably a regression introduced by #916. since the devsite references the `helix-cli` in the `package.json`, the module resolution might be wrong...

**Comment by tripodsan** [comment]
it seems like the `package.json` is missing in the zip...
